# Rendering mode of items on shops. Can be: QUANTITY, STACK, SINGLE or NONE
display-mode: QUANTITY

# Maximum amount of items a shop can keep in stock at one time.
max-stock: 99999

# Item used for creating or deleting shops.
item: minecraft:stick

# Options for the database
database:
  # SQLite3 connection url
  url: "jdbc:sqlite:plugins/Slabby/slabby.db"

# Defaults for new shops.
defaults:
  # Default buy price for new shops.
  buy-price: 0
  # Default sell price for new shops.
  sell-price: 0
  # Default quantity for new shops.
  quantity: 64
  # Default note for new shops.
  note: Let's trade!

# Options for restocking shops.
restock:
  # Options for shop punching.
  punch:
    # Owners can punch their shop to restock items.
    enabled: true
    # Owners can punch their shop while crouching to restock all items at once.
    bulk: true
    # Owners can punch their shop with a shulker box to restock using the matching items within.
    shulker: true
  # Options for chest linking.
  chests:
    # Chests can be linked to a shop.
    enabled: true
    # Options for refilling linked chests
    hoppers:
      # Hoppers can refill a linked chest.
      enabled: true
