[versions]
adventure = "4.17.0"
sqlite-jdbc = "3.46.0.0"
ormlite-jdbc = "6.1"
lombok = "1.18.34"
shadow = "8.3.0"
paper = "1.21-R0.1-SNAPSHOT"
plugin-annotations = "1.2.3-SNAPSHOT"
acf-paper = "0.5.1-SNAPSHOT"
vault = "1.7"
configurate-yaml = "4.1.2"
invui = "1.33"
lands-api = "6.44.10"
gson = "2.11.0"

[libraries]
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
ormlite-jdbc = { module = "com.j256.ormlite:ormlite-jdbc", version.ref = "ormlite-jdbc" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
plugin-annotations = { module = "org.spigotmc:plugin-annotations", version.ref  = "plugin-annotations" }
acf-paper = { module = "co.aikar:acf-paper", version.ref = "acf-paper" }
vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate-yaml" }
invui = { module = "xyz.xenondevs.invui:invui", version.ref = "invui" }
lands-api = { module = "com.github.angeschossen:LandsAPI", version.ref = "lands-api" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[bundles]
sqlite = ["sqlite-jdbc", "ormlite-jdbc"]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }